name: Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Executa todo dia à meia-noite UTC
  workflow_dispatch: # Permite acionamento manual
  push: # Executa em cada push para a branch principal
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Concede permissão de escrita ao GITHUB_TOKEN

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Por padrão, a ação gera os arquivos SVG na pasta 'dist/'
          # Você pode adicionar outras opções aqui, se quiser personalizar o gráfico (cores, etc.)

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist # Adiciona os arquivos gerados da pasta 'dist'
          git commit -m "chore: update pacman contribution graph" || echo "No changes to commit"
          git push
